# -*- coding: utf-8 -*-
"""csvread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT27gp--k0Za7MN_UQ53O2upY_jcqBCq
"""

pathd='drive/MyDrive/TSLA.csv'# path for file on my device plz chance for whom that gonna test

from google.colab import drive
drive.mount('/content/drive')

#this version is specifically for colab so it's easier to run without setting up all the local environment

import pandas as pd # what i usually use
df=pd.read_csv(pathd)
df

# laod df

from matplotlib import pyplot as plt

plt.rcParams["figure.figsize"] = [7.00, 3.50]
plt.rcParams["figure.autolayout"] = True
columns = ["Date", "Open"]
df=pd.read_csv(pathd)
print("Contents in csv file: ", df)
plt.plot(df.Date, df.Open)
plt.show()