# -*- coding: utf-8 -*-
"""prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9xSL044ZiZnWm3lCICtenRGgo41gm7Z
"""

"""
You will ask the user to input their full name and a minimum price. Then you will create a list of prices
(be sure you add a range of prices to your list). Loop through your price list to add up all the values in
the list and count all values greater than the minimum price.
Print out the user name, the minimum price, the count of prices greater than the minimum price, and the total price

"""
count=0
sum=0
full_name = input("what's ur name?")
min_price = float(input("what's ur min price?"))
price_list = [69.0, 71.0, 84.5, 91.0, 67.4, 81.2, 84.6, 58.8, 79.3, 101.2]
#test
#print(count,sum,full_name,min_price,price_list[0])
for price in price_list:
    sum += price
    if price > min_price:
        count += 1
print(f"Hello {full_name},the minimum price is {min_price}")
print(f"There are {count} prices greater than the minimum price")
print(f"There total price is {round(sum,2)}")#due to price only can have 2 digit after .